### ISSUE TITLE
تغییر در نحوه خلاصه گذاری

### ISSUE THREAD

**Issue by DHosseiny** [PBR-Group/effective-java#1]
سلام
به نظرم بهتره از عنوان انگلیسی به جای فارسی استفاده کنیم که
Searchableتر
بشه چون ممکنه هر کسی عنوان آیتم و ی جوری ترجمه کنه.
خیلی ممنون

**Comment by abbas-oveissi** [comment]
<div dir="rtl">
سلام، من به دو دلیل اینکارو نکردم.

 ۱- وقتی محتوا فارسی هس بنظرم بهتره عنوان هم فارسی باشه، کسی که دنبال محتوای فارسی هس همه چیو فارسی سرچ میکنه. کسی هم که فقط یه آیتم خاص رو میخواد با شماره آیتم میتونه بهش برسه.

۲-توی قالب نمایش دادنش زشت میشه. چون بخشی از محتوا فارسی ولی عنوان انگلیسیه

حالا میشه توی گروه در موردش بحث کرد و تصمیم بگیریم
</div>

**Comment by abbas-oveissi** [comment]
<div dir="rtl">
من این issue رو فعلا می‌بندم، اگر کسی در این رابطه نظر داشت، باز بکنه
</div>
